[package]
name = "imaging_fractals"
version = "0.1.0"
edition = "2021"
crate-type = ["dylib"]
rustflags = ["-L", ".", "-l", "Sierp"]

[dependencies]
libc = "0.2.0"
ppmitzador = { path = "../../ppmitzador" }
